/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Thu Dec 10 10:16:47 2015. */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Algorithm {
    Algorithm_BIP32 = 0,
    Algorithm_ELECTRUM = 1
} Algorithm;

/* Struct definitions */
typedef struct _Bulk {
    pb_callback_t bulk;
} Bulk;

typedef struct _ButtonAck {
    uint8_t dummy_field;
} ButtonAck;

typedef struct _ButtonCancel {
    uint8_t dummy_field;
} ButtonCancel;

typedef struct _ButtonRequest {
    uint8_t dummy_field;
} ButtonRequest;

typedef struct _ChangeEncryptionKey {
    pb_callback_t password;
} ChangeEncryptionKey;

typedef struct _Entropy {
    pb_callback_t entropy;
} Entropy;

typedef struct _GetBulk {
    uint8_t dummy_field;
} GetBulk;

typedef struct _GetDeviceUUID {
    uint8_t dummy_field;
} GetDeviceUUID;

typedef struct _GetMasterPublicKey {
    uint8_t dummy_field;
} GetMasterPublicKey;

typedef struct _ListWallets {
    uint8_t dummy_field;
} ListWallets;

typedef struct _OtpCancel {
    uint8_t dummy_field;
} OtpCancel;

typedef struct _OtpRequest {
    uint8_t dummy_field;
} OtpRequest;

typedef struct _PinAck {
    pb_callback_t password;
} PinAck;

typedef struct _PinCancel {
    uint8_t dummy_field;
} PinCancel;

typedef struct _PinRequest {
    uint8_t dummy_field;
} PinRequest;

typedef struct _ResetLang {
    uint8_t dummy_field;
} ResetLang;

typedef struct _ResetPIN {
    uint8_t dummy_field;
} ResetPIN;

typedef struct _ScanWallet {
    uint8_t dummy_field;
} ScanWallet;

typedef struct _SignTransactionExtended {
    pb_callback_t address_handle_extended;
    pb_callback_t transaction_data;
} SignTransactionExtended;

typedef struct _SignatureComplete {
    pb_callback_t signature_complete_data;
} SignatureComplete;

typedef struct _Success {
    uint8_t dummy_field;
} Success;

typedef struct _Wallets {
    pb_callback_t wallet_info;
} Wallets;

typedef PB_BYTES_ARRAY_T(65) Address_public_key_t;

typedef PB_BYTES_ARRAY_T(20) Address_address_t;

typedef struct _Address {
    uint32_t address_handle;
    Address_public_key_t public_key;
    Address_address_t address;
} Address;

typedef struct _AddressHandleExtended {
    uint32_t address_handle_root;
    uint32_t address_handle_chain;
    uint32_t address_handle_index;
} AddressHandleExtended;

typedef PB_BYTES_ARRAY_T(33) AddressPubKey_public_key_t;

typedef struct _AddressPubKey {
    AddressPubKey_public_key_t public_key;
} AddressPubKey;

typedef struct _BackupWallet {
    bool has_is_encrypted;
    bool is_encrypted;
    bool has_device;
    uint32_t device;
} BackupWallet;

typedef PB_BYTES_ARRAY_T(40) ChangeDeviceName_device_name_t;

typedef struct _ChangeDeviceName {
    ChangeDeviceName_device_name_t device_name;
} ChangeDeviceName;

typedef PB_BYTES_ARRAY_T(40) ChangeWalletName_wallet_name_t;

typedef struct _ChangeWalletName {
    ChangeWalletName_wallet_name_t wallet_name;
} ChangeWalletName;

typedef struct _CurrentWalletXPUB {
    char xpub[112];
} CurrentWalletXPUB;

typedef struct _DeleteWallet {
    bool has_wallet_handle;
    uint32_t wallet_handle;
} DeleteWallet;

typedef PB_BYTES_ARRAY_T(16) DeviceUUID_device_uuid_t;

typedef struct _DeviceUUID {
    DeviceUUID_device_uuid_t device_uuid;
} DeviceUUID;

typedef struct _DisplayAddressAsQR {
    bool has_address_handle_index;
    uint32_t address_handle_index;
} DisplayAddressAsQR;

typedef struct _Failure {
    uint32_t error_code;
    pb_callback_t error_message;
} Failure;

typedef PB_BYTES_ARRAY_T(64) Features_echoed_session_id_t;

typedef PB_BYTES_ARRAY_T(40) Features_device_name_t;

typedef struct _Features {
    Features_echoed_session_id_t echoed_session_id;
    pb_callback_t vendor;
    bool has_major_version;
    uint32_t major_version;
    bool has_minor_version;
    uint32_t minor_version;
    pb_callback_t config;
    bool has_otp;
    bool otp;
    bool has_pin;
    bool pin;
    bool has_spv;
    bool spv;
    pb_size_t algo_count;
    Algorithm algo[2];
    bool has_debug_link;
    bool debug_link;
    bool has_is_formatted;
    bool is_formatted;
    bool has_device_name;
    Features_device_name_t device_name;
} Features;

typedef PB_BYTES_ARRAY_T(32) FormatWalletArea_initial_entropy_pool_t;

typedef struct _FormatWalletArea {
    FormatWalletArea_initial_entropy_pool_t initial_entropy_pool;
} FormatWalletArea;

typedef struct _GetAddressAndPublicKey {
    uint32_t address_handle;
} GetAddressAndPublicKey;

typedef struct _GetEntropy {
    uint32_t number_of_bytes;
} GetEntropy;

typedef PB_BYTES_ARRAY_T(64) Initialize_session_id_t;

typedef struct _Initialize {
    Initialize_session_id_t session_id;
} Initialize;

typedef struct _LoadWallet {
    bool has_wallet_number;
    uint32_t wallet_number;
} LoadWallet;

typedef PB_BYTES_ARRAY_T(65) MasterPublicKey_public_key_t;

typedef PB_BYTES_ARRAY_T(32) MasterPublicKey_chain_code_t;

typedef struct _MasterPublicKey {
    MasterPublicKey_public_key_t public_key;
    MasterPublicKey_chain_code_t chain_code;
} MasterPublicKey;

typedef PB_BYTES_ARRAY_T(40) NewWallet_wallet_name_t;

typedef struct _NewWallet {
    bool has_wallet_number;
    uint32_t wallet_number;
    pb_callback_t password;
    bool has_wallet_name;
    NewWallet_wallet_name_t wallet_name;
    bool has_is_hidden;
    bool is_hidden;
} NewWallet;

typedef struct _OtpAck {
    char otp[16];
} OtpAck;

typedef struct _Ping {
    bool has_greeting;
    char greeting[512];
} Ping;

typedef PB_BYTES_ARRAY_T(64) PingResponse_echoed_session_id_t;

typedef struct _PingResponse {
    bool has_echoed_greeting;
    char echoed_greeting[512];
    PingResponse_echoed_session_id_t echoed_session_id;
} PingResponse;

typedef PB_BYTES_ARRAY_T(21232) SetBulk_bulk_t;

typedef struct _SetBulk {
    SetBulk_bulk_t bulk;
} SetBulk;

typedef struct _SetChangeAddressIndex {
    bool has_address_handle_index;
    uint32_t address_handle_index;
} SetChangeAddressIndex;

typedef PB_BYTES_ARRAY_T(109) SignatureCompleteData_signature_data_complete_t;

typedef struct _SignatureCompleteData {
    SignatureCompleteData_signature_data_complete_t signature_data_complete;
} SignatureCompleteData;

typedef PB_BYTES_ARRAY_T(1024) SignatureMessage_signature_data_complete_message_t;

typedef struct _SignatureMessage {
    SignatureMessage_signature_data_complete_message_t signature_data_complete_message;
} SignatureMessage;

typedef PB_BYTES_ARRAY_T(40) WalletInfo_wallet_name_t;

typedef PB_BYTES_ARRAY_T(16) WalletInfo_wallet_uuid_t;

typedef struct _WalletInfo {
    uint32_t wallet_number;
    WalletInfo_wallet_name_t wallet_name;
    WalletInfo_wallet_uuid_t wallet_uuid;
    bool has_version;
    uint32_t version;
} WalletInfo;

typedef PB_BYTES_ARRAY_T(64) RestoreWallet_seed_t;

typedef struct _RestoreWallet {
    NewWallet new_wallet;
    RestoreWallet_seed_t seed;
} RestoreWallet;

typedef struct _SignMessage {
    AddressHandleExtended address_handle_extended;
    pb_callback_t message_data;
} SignMessage;

/* Default values for struct fields */
extern const uint32_t DeleteWallet_wallet_handle_default;
extern const uint32_t NewWallet_wallet_number_default;
extern const bool NewWallet_is_hidden_default;
extern const uint32_t LoadWallet_wallet_number_default;
extern const bool BackupWallet_is_encrypted_default;
extern const uint32_t BackupWallet_device_default;

/* Initializer values for message structs */
#define Initialize_init_default                  {{0, {0}}}
#define Features_init_default                    {{0, {0}}, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, 0, {(Algorithm)0, (Algorithm)0}, false, 0, false, 0, false, {0, {0}}}
#define Ping_init_default                        {false, ""}
#define PingResponse_init_default                {false, "", {0, {0}}}
#define Success_init_default                     {0}
#define Failure_init_default                     {0, {{NULL}, NULL}}
#define ButtonRequest_init_default               {0}
#define ButtonAck_init_default                   {0}
#define ButtonCancel_init_default                {0}
#define PinRequest_init_default                  {0}
#define PinAck_init_default                      {{{NULL}, NULL}}
#define PinCancel_init_default                   {0}
#define OtpRequest_init_default                  {0}
#define OtpAck_init_default                      {""}
#define OtpCancel_init_default                   {0}
#define DeleteWallet_init_default                {false, 0u}
#define NewWallet_init_default                   {false, 0u, {{NULL}, NULL}, false, {0, {0}}, false, false}
#define Address_init_default                     {0, {0, {0}}, {0, {0}}}
#define AddressPubKey_init_default               {{0, {0}}}
#define GetAddressAndPublicKey_init_default      {0}
#define AddressHandleExtended_init_default       {0, 0, 0}
#define SignTransactionExtended_init_default     {{{NULL}, NULL}, {{NULL}, NULL}}
#define SignatureCompleteData_init_default       {{0, {0}}}
#define SignatureComplete_init_default           {{{NULL}, NULL}}
#define LoadWallet_init_default                  {false, 0u}
#define FormatWalletArea_init_default            {{0, {0}}}
#define ChangeEncryptionKey_init_default         {{{NULL}, NULL}}
#define ChangeWalletName_init_default            {{0, {0}}}
#define ChangeDeviceName_init_default            {{0, {0}}}
#define ListWallets_init_default                 {0}
#define WalletInfo_init_default                  {0, {0, {0}}, {0, {0}}, false, 0}
#define Wallets_init_default                     {{{NULL}, NULL}}
#define BackupWallet_init_default                {false, false, false, 0u}
#define RestoreWallet_init_default               {NewWallet_init_default, {0, {0}}}
#define GetDeviceUUID_init_default               {0}
#define DeviceUUID_init_default                  {{0, {0}}}
#define GetEntropy_init_default                  {0}
#define Entropy_init_default                     {{{NULL}, NULL}}
#define GetBulk_init_default                     {0}
#define Bulk_init_default                        {{{NULL}, NULL}}
#define SetBulk_init_default                     {{0, {0}}}
#define GetMasterPublicKey_init_default          {0}
#define MasterPublicKey_init_default             {{0, {0}}, {0, {0}}}
#define ResetLang_init_default                   {0}
#define ResetPIN_init_default                    {0}
#define ScanWallet_init_default                  {0}
#define CurrentWalletXPUB_init_default           {""}
#define SignMessage_init_default                 {AddressHandleExtended_init_default, {{NULL}, NULL}}
#define SignatureMessage_init_default            {{0, {0}}}
#define DisplayAddressAsQR_init_default          {false, 0}
#define SetChangeAddressIndex_init_default       {false, 0}
#define Initialize_init_zero                     {{0, {0}}}
#define Features_init_zero                       {{0, {0}}, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, 0, {(Algorithm)0, (Algorithm)0}, false, 0, false, 0, false, {0, {0}}}
#define Ping_init_zero                           {false, ""}
#define PingResponse_init_zero                   {false, "", {0, {0}}}
#define Success_init_zero                        {0}
#define Failure_init_zero                        {0, {{NULL}, NULL}}
#define ButtonRequest_init_zero                  {0}
#define ButtonAck_init_zero                      {0}
#define ButtonCancel_init_zero                   {0}
#define PinRequest_init_zero                     {0}
#define PinAck_init_zero                         {{{NULL}, NULL}}
#define PinCancel_init_zero                      {0}
#define OtpRequest_init_zero                     {0}
#define OtpAck_init_zero                         {""}
#define OtpCancel_init_zero                      {0}
#define DeleteWallet_init_zero                   {false, 0}
#define NewWallet_init_zero                      {false, 0, {{NULL}, NULL}, false, {0, {0}}, false, 0}
#define Address_init_zero                        {0, {0, {0}}, {0, {0}}}
#define AddressPubKey_init_zero                  {{0, {0}}}
#define GetAddressAndPublicKey_init_zero         {0}
#define AddressHandleExtended_init_zero          {0, 0, 0}
#define SignTransactionExtended_init_zero        {{{NULL}, NULL}, {{NULL}, NULL}}
#define SignatureCompleteData_init_zero          {{0, {0}}}
#define SignatureComplete_init_zero              {{{NULL}, NULL}}
#define LoadWallet_init_zero                     {false, 0}
#define FormatWalletArea_init_zero               {{0, {0}}}
#define ChangeEncryptionKey_init_zero            {{{NULL}, NULL}}
#define ChangeWalletName_init_zero               {{0, {0}}}
#define ChangeDeviceName_init_zero               {{0, {0}}}
#define ListWallets_init_zero                    {0}
#define WalletInfo_init_zero                     {0, {0, {0}}, {0, {0}}, false, 0}
#define Wallets_init_zero                        {{{NULL}, NULL}}
#define BackupWallet_init_zero                   {false, 0, false, 0}
#define RestoreWallet_init_zero                  {NewWallet_init_zero, {0, {0}}}
#define GetDeviceUUID_init_zero                  {0}
#define DeviceUUID_init_zero                     {{0, {0}}}
#define GetEntropy_init_zero                     {0}
#define Entropy_init_zero                        {{{NULL}, NULL}}
#define GetBulk_init_zero                        {0}
#define Bulk_init_zero                           {{{NULL}, NULL}}
#define SetBulk_init_zero                        {{0, {0}}}
#define GetMasterPublicKey_init_zero             {0}
#define MasterPublicKey_init_zero                {{0, {0}}, {0, {0}}}
#define ResetLang_init_zero                      {0}
#define ResetPIN_init_zero                       {0}
#define ScanWallet_init_zero                     {0}
#define CurrentWalletXPUB_init_zero              {""}
#define SignMessage_init_zero                    {AddressHandleExtended_init_zero, {{NULL}, NULL}}
#define SignatureMessage_init_zero               {{0, {0}}}
#define DisplayAddressAsQR_init_zero             {false, 0}
#define SetChangeAddressIndex_init_zero          {false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Bulk_bulk_tag                            1
#define ChangeEncryptionKey_password_tag         1
#define Entropy_entropy_tag                      1
#define PinAck_password_tag                      1
#define SignTransactionExtended_address_handle_extended_tag 1
#define SignTransactionExtended_transaction_data_tag 2
#define SignatureComplete_signature_complete_data_tag 1
#define Wallets_wallet_info_tag                  1
#define Address_address_handle_tag               1
#define Address_public_key_tag                   2
#define Address_address_tag                      3
#define AddressHandleExtended_address_handle_root_tag 1
#define AddressHandleExtended_address_handle_chain_tag 2
#define AddressHandleExtended_address_handle_index_tag 3
#define AddressPubKey_public_key_tag             1
#define BackupWallet_is_encrypted_tag            1
#define BackupWallet_device_tag                  2
#define ChangeDeviceName_device_name_tag         1
#define ChangeWalletName_wallet_name_tag         1
#define CurrentWalletXPUB_xpub_tag               1
#define DeleteWallet_wallet_handle_tag           1
#define DeviceUUID_device_uuid_tag               1
#define DisplayAddressAsQR_address_handle_index_tag 1
#define Failure_error_code_tag                   1
#define Failure_error_message_tag                2
#define Features_echoed_session_id_tag           1
#define Features_vendor_tag                      2
#define Features_major_version_tag               3
#define Features_minor_version_tag               4
#define Features_config_tag                      5
#define Features_otp_tag                         6
#define Features_pin_tag                         7
#define Features_spv_tag                         8
#define Features_algo_tag                        9
#define Features_debug_link_tag                  10
#define Features_is_formatted_tag                11
#define Features_device_name_tag                 12
#define FormatWalletArea_initial_entropy_pool_tag 1
#define GetAddressAndPublicKey_address_handle_tag 1
#define GetEntropy_number_of_bytes_tag           1
#define Initialize_session_id_tag                1
#define LoadWallet_wallet_number_tag             1
#define MasterPublicKey_public_key_tag           1
#define MasterPublicKey_chain_code_tag           2
#define NewWallet_wallet_number_tag              1
#define NewWallet_password_tag                   2
#define NewWallet_wallet_name_tag                3
#define NewWallet_is_hidden_tag                  4
#define OtpAck_otp_tag                           1
#define Ping_greeting_tag                        1
#define PingResponse_echoed_greeting_tag         1
#define PingResponse_echoed_session_id_tag       2
#define SetBulk_bulk_tag                         1
#define SetChangeAddressIndex_address_handle_index_tag 1
#define SignatureCompleteData_signature_data_complete_tag 1
#define SignatureMessage_signature_data_complete_message_tag 1
#define WalletInfo_wallet_number_tag             1
#define WalletInfo_wallet_name_tag               2
#define WalletInfo_wallet_uuid_tag               3
#define WalletInfo_version_tag                   4
#define RestoreWallet_new_wallet_tag             1
#define RestoreWallet_seed_tag                   2
#define SignMessage_address_handle_extended_tag  1
#define SignMessage_message_data_tag             2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Initialize_fields[2];
extern const pb_field_t Features_fields[13];
extern const pb_field_t Ping_fields[2];
extern const pb_field_t PingResponse_fields[3];
extern const pb_field_t Success_fields[1];
extern const pb_field_t Failure_fields[3];
extern const pb_field_t ButtonRequest_fields[1];
extern const pb_field_t ButtonAck_fields[1];
extern const pb_field_t ButtonCancel_fields[1];
extern const pb_field_t PinRequest_fields[1];
extern const pb_field_t PinAck_fields[2];
extern const pb_field_t PinCancel_fields[1];
extern const pb_field_t OtpRequest_fields[1];
extern const pb_field_t OtpAck_fields[2];
extern const pb_field_t OtpCancel_fields[1];
extern const pb_field_t DeleteWallet_fields[2];
extern const pb_field_t NewWallet_fields[5];
extern const pb_field_t Address_fields[4];
extern const pb_field_t AddressPubKey_fields[2];
extern const pb_field_t GetAddressAndPublicKey_fields[2];
extern const pb_field_t AddressHandleExtended_fields[4];
extern const pb_field_t SignTransactionExtended_fields[3];
extern const pb_field_t SignatureCompleteData_fields[2];
extern const pb_field_t SignatureComplete_fields[2];
extern const pb_field_t LoadWallet_fields[2];
extern const pb_field_t FormatWalletArea_fields[2];
extern const pb_field_t ChangeEncryptionKey_fields[2];
extern const pb_field_t ChangeWalletName_fields[2];
extern const pb_field_t ChangeDeviceName_fields[2];
extern const pb_field_t ListWallets_fields[1];
extern const pb_field_t WalletInfo_fields[5];
extern const pb_field_t Wallets_fields[2];
extern const pb_field_t BackupWallet_fields[3];
extern const pb_field_t RestoreWallet_fields[3];
extern const pb_field_t GetDeviceUUID_fields[1];
extern const pb_field_t DeviceUUID_fields[2];
extern const pb_field_t GetEntropy_fields[2];
extern const pb_field_t Entropy_fields[2];
extern const pb_field_t GetBulk_fields[1];
extern const pb_field_t Bulk_fields[2];
extern const pb_field_t SetBulk_fields[2];
extern const pb_field_t GetMasterPublicKey_fields[1];
extern const pb_field_t MasterPublicKey_fields[3];
extern const pb_field_t ResetLang_fields[1];
extern const pb_field_t ResetPIN_fields[1];
extern const pb_field_t ScanWallet_fields[1];
extern const pb_field_t CurrentWalletXPUB_fields[2];
extern const pb_field_t SignMessage_fields[3];
extern const pb_field_t SignatureMessage_fields[2];
extern const pb_field_t DisplayAddressAsQR_fields[2];
extern const pb_field_t SetChangeAddressIndex_fields[2];

/* Maximum encoded size of messages (where known) */
#define Initialize_size                          66
#define Ping_size                                515
#define PingResponse_size                        581
#define Success_size                             0
#define ButtonRequest_size                       0
#define ButtonAck_size                           0
#define ButtonCancel_size                        0
#define PinRequest_size                          0
#define PinCancel_size                           0
#define OtpRequest_size                          0
#define OtpAck_size                              18
#define OtpCancel_size                           0
#define DeleteWallet_size                        6
#define Address_size                             95
#define AddressPubKey_size                       35
#define GetAddressAndPublicKey_size              6
#define AddressHandleExtended_size               18
#define SignatureCompleteData_size               111
#define LoadWallet_size                          6
#define FormatWalletArea_size                    34
#define ChangeWalletName_size                    42
#define ChangeDeviceName_size                    42
#define ListWallets_size                         0
#define WalletInfo_size                          72
#define BackupWallet_size                        8
#define GetDeviceUUID_size                       0
#define DeviceUUID_size                          18
#define GetEntropy_size                          6
#define GetBulk_size                             0
#define SetBulk_size                             21236
#define GetMasterPublicKey_size                  0
#define MasterPublicKey_size                     101
#define ResetLang_size                           0
#define ResetPIN_size                            0
#define ScanWallet_size                          0
#define CurrentWalletXPUB_size                   114
#define SignatureMessage_size                    1027
#define DisplayAddressAsQR_size                  6
#define SetChangeAddressIndex_size               6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
